version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: kamilcraft-api_www
    working_dir: /application
    ports:
      - "80:80"
    volumes:
      - .:/application
      - ./config/docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - localnet

  php:
    build:
      args:
          USER_UID: ${USER_UID}
          USER_NAME: ${USER_NAME}
      context: ./config/docker/dev/php
    container_name: kamilcraft-api_php8
    working_dir: /application
    volumes:
      - .:/application
    networks:
      - localnet

networks:
    localnet:
        driver: bridge
